<!-- 
     (IndexFrame)
     Generated by MCM Software Solutions, Inc.
      JEvolution Studio ®  v 3.6.0.0 J2EE 1.4 Build 406-20110601120000 
     Copyright © 2008 http://www.mcmsoftware.com
     All Rights Reserved.
 -->

<%@ page language="java" session="true"  import="java.util.*" %>
<%
HttpSession sessions = request.getSession();
if(request.getSession().getAttribute("intomobile") == null)
	sessions.invalidate();
%>
<head>
	<title>Frame Menu </title>
	<script language="JavaScript">
		var indi_frame_menu = 0;
	</script>
</head>
<FRAMESET FRAMEBORDER="0" FRAMESPACING="1" BORDER="0" rows="100%">
<FRAMESET FRAMEBORDER="0" FRAMESPACING="1" BORDER="0" id="framemenu" cols="25%,*">
	<FRAME SRC="210ME2.html" NAME="menu" target="contenido" scrolling="auto">
<FRAME SRC="" NAME="contenido">
</FRAMESET>
</FRAMESET>
