<!-- 
     MCMfw210DD25XLS.jsp
     Generated by MCM Software Solutions, Inc.
      JEvolution Studio ®  v 3.6.0.0 J2EE 1.4 Build 406-20110601120000 
     Copyright © 2008 http://www.mcmsoftware.com
     All Rights Reserved.
 -->

<% String country = request.getParameter("@country"); %>
<% String state = request.getParameter("@state"); %>
<% String city = request.getParameter("@city"); %>
<% String type = request.getParameter("@type"); %>
<% String newsdate = request.getParameter("@newsdate"); %>
<% response.sendRedirect("http://"+request.getServerName()+":"+request.getServerPort()+request.getContextPath()+"/LogicServerAppServlet?NameXLS=12BWF210SC25XLS&sourceXBRF=21021033brf&Function=EXCELFORMAT&@country="+country+"&@state="+state+"&@city="+city+"&@type="+type+"&@newsdate="+newsdate+"" ); %>