<!-- 
     MCMfw210DD20.jsp
     Generated by MCM Software Solutions, Inc.
      JEvolution Studio ®  v 3.6.0.0 J2EE 1.4 Build 406-20110601120000 
     Copyright © 2008 http://www.mcmsoftware.com
     All Rights Reserved.
 -->

<% String country = request.getParameter("@country"); %>
<% String state = request.getParameter("@state"); %>
<% String city = request.getParameter("@city"); %>
<% String type = request.getParameter("@type"); %>
<% String newsdate = request.getParameter("@newsdate"); %>
<html>
	<jsp:forward page="/LogicServerAppServlet">
		<jsp:param name="NameXSL" value="23BWF210SC20"/>
		<jsp:param name="NameBODY" value="210DD20"/>
		<jsp:param name="sourceXBRF" value="21021021brf"/>
		<jsp:param name="Function" value="XBRFResolver"/>
		<jsp:param name="@country" value="<%= country %>"/>
		<jsp:param name="@state" value="<%= state %>"/>
		<jsp:param name="@city" value="<%= city %>"/>
		<jsp:param name="@type" value="<%= type %>"/>
		<jsp:param name="@newsdate" value="<%= newsdate %>"/>
	</jsp:forward>
</html>