<!-- 
     MCMfw210DD41.jsp
     Generated by MCM Software Solutions, Inc.
      JEvolution Studio ®  v 3.6.0.0 J2EE 1.4 Build 406-20110601120000 
     Copyright © 2008 http://www.mcmsoftware.com
     All Rights Reserved.
 -->

<% String country = request.getParameter("@country"); %>
<% String type = request.getParameter("@type"); %>
<% String state = request.getParameter("@state"); %>
<html>
	<jsp:forward page="/LogicServerAppServlet">
		<jsp:param name="NameXSL" value="23BWF210SC39"/>
		<jsp:param name="NameBODY" value="210DD41"/>
		<jsp:param name="sourceXBRF" value="21021051brf"/>
		<jsp:param name="Function" value="XBRFResolver"/>
		<jsp:param name="@country" value="<%= country %>"/>
		<jsp:param name="@type" value="<%= type %>"/>
		<jsp:param name="@state" value="<%= state %>"/>
	</jsp:forward>
</html>