/** 
 * servletTable610LT1
 * Generated by MCM Software Solutions, Inc.
 *  JEvolution Studio ®  v 3.6.0.0 J2EE 1.4 Build 406-20110601120000 
 * Copyright © 2008 http://www.mcmsoftware.com
 * All Rights Reserved.
 */

package com.mcmsoftware.project;
import java.io.IOException;
import java.sql.Connection;
import java.util.Enumeration;
import java.util.Hashtable;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.mcmsoftware.jevolution.logicserver.basics.LogicServerErrorManager;
import com.mcmsoftware.jevolution.logicserver.interfaces.LogicServerErrors;
import com.mcmsoftware.jevolution.logicserver.jpool.PoolManager;
import com.mcmsoftware.jevolution.logicserver.process.LogicServerServlet;
import com.mcmsoftware.jevolution.logicserver.process.XmlConfigFileReader;
import com.mcmsoftware.project.beanLogins;

/** 
 *  Creation date: (2011/10/24 9:26:38 AM)
 *  @author:JEVOLUTION
 */

public class servletTable610LT1 extends HttpServlet implements LogicServerErrors{
	public void doGet(HttpServletRequest request,HttpServletResponse response) throws ServletException,IOException{
		doPost(request,response);
	};
	public void displayLogicServerConsole(HttpServletRequest request,HttpServletResponse response,String strException,int iError) {
		try{
			String e;
			LogicServerErrorManager aLogicServerErrorManager;
			aLogicServerErrorManager = new LogicServerErrorManager();
			request.setAttribute("ErrorMessage","Servlet: servletTable610LT1 ");
			request.setAttribute("Exception",strException);
			request.setAttribute("Advice",aLogicServerErrorManager.getErrorMessage(iError));
			e = "/jsp/LogicServerConsole.jsp?";
			getServletContext().getRequestDispatcher(e).forward(request,response);
		}
		catch(Throwable edisplayLogicServerConsole){
			System.out.println(edisplayLogicServerConsole.toString());
		}
	}
	public void doPost(HttpServletRequest request,HttpServletResponse response) throws ServletException,IOException{
		Connection con;
		Enumeration eValues;
		Hashtable htValues;
		PoolManager poolMan;
		String strApplicationName;
		String nameConnection;
		String user;
		String password;
		String typeLogin;
		String ipAddress;
		String label, value;
		strApplicationName = request.getContextPath().substring(1);
		nameConnection = XmlConfigFileReader.searchLabel("<NameCx>","610LT1",strApplicationName);
		try{
			poolMan = LogicServerServlet.getPoolManagerInstance(request,strApplicationName);
			if(poolMan == null){
				displayLogicServerConsole(request,response,"The Logic Server has not been registrated",REGISTRATIONERROR);
				return;
			};
			con = poolMan.getConnection(nameConnection);
			response.setContentType("text/html");
			try{
				user     = request.getParameter("user");
				password = request.getParameter("password");
				typeLogin = request.getParameter("typeLogin");
				ipAddress= request.getRemoteAddr();
				beanLogins  beanvalidator = new beanLogins(user,password,ipAddress);
				beanvalidator = beanvalidator.validateAndLoadSesion(con,beanvalidator);
				if( beanvalidator != null){
					HttpSession session = request.getSession();
					Hashtable   htSessionParams = new Hashtable(); 
					htSessionParams   = (Hashtable)request.getSession().getAttribute("htParamsSession"); 
					session.invalidate();
					if(htSessionParams !=null)	 
						request.getSession().setAttribute("htParamsSession",htSessionParams);
					session = request.getSession();
					session.setAttribute("typeLogin",typeLogin);
					/**setBean Sesion**/
					session.setAttribute("User",beanvalidator);
					session.setMaxInactiveInterval(150);
					response.sendRedirect(request.getContextPath() + "/jsp/MCM610SS1.jsp");
					poolMan.freeConnection(nameConnection,con);
				}
				else{
					response.sendRedirect(request.getContextPath() + "/jsp/index.jsp?error=Text Error");
					poolMan.freeConnection(nameConnection,con);
				}
			}
			catch(Exception er){
				displayLogicServerConsole(request,response,er.toString(),LOGINERROR);			}
		}
		catch(Exception es){
				displayLogicServerConsole(request,response,es.toString(),LOGINERROR);
		}
	}
}
