# Archivo de configuracion del LogicServer 

appServer.name    = Jakarta-Tomcat
appServer.version = 6.x
appServer.home = "C:\\Program Files (x86)\\Apache Software Foundation\\Tomcat 6.0\\webapps"
appServer.port = 8280
appServer.media = "C:\\Program Files (x86)\\Apache Software Foundation\\Tomcat 6.0\\conf"
appServer.webApps = "C:\\Program Files (x86)\\Apache Software Foundation\\Tomcat 6.0\\webapps"
appServer.logs = "C:\\Program Files (x86)\\Apache Software Foundation\\Tomcat 6.0\\logs"
appServer.port = 8280
documentVersion = 1.0