# Archivo de configuracion del LogicServer 

appServer.name    = Jakarta-Tomcat
appServer.version = 11.x
appServer.home = "/usr/local/tomcat/webapps"
appServer.port = 8080
appServer.media = "/usr/local/tomcat/conf"
appServer.webApps = "/usr/local/tomcat/webapps"
appServer.logs = "/usr/local/tomcat/logs"
appServer.port = 8080
documentVersion = 1.0