# Load mod_jk module
# Update this path to match your modules location
LoadModule jk_module modules/mod_jk.so

# Where to find workers.properties
# Update this path to match your conf directory location
JkWorkersFile "C:/Program Files (x86)/Apache Software Foundation/Tomcat 6.0/conf/workers.properties"

# Where to put jk logs
# Update this path to match your logs directory location
JkLogFile "C:/Program Files (x86)/Apache Software Foundation/Tomcat 6.0/logs/mod_jk.log"

# Set the jk log level [debug/error/info]
JkLogLevel info

# Select the log format
JkLogStampFormat "[%a %b %d %H:%M:%S %Y]"

# JkOptions indicate to send SSL KEY SIZE,
JkOptions +ForwardKeySize +ForwardURICompat -ForwardDirectories

# JkRequestLogFormat set the request format
JkRequestLogFormat "%w %V %T"

# Send everything for context /ws to worker ajp13
JkMount /ws ajp13
JkMount /ws/* ajp13 

# Send everything for context /jsp-examples to worker ajp13
JkMount /jsp-examples ajp13
JkMount /jsp-examples/* ajp13 

# Send everything for context /servelts-examples to worker ajp13
JkMount /servlets-examples ajp13
JkMount /servlets-examples/* ajp13

# Send everything for context /Razient to worker ajp13
JkMount /Razient ajp13
JkMount /Razient/* ajp13 
JkMount /Razient/*.jsp ajp13
JkMount /Razient/css/* ajp13
JkMount /Razient/css/images/* ajp13
JkMount /Razient/css/images/login/* ajp13
JkMount /Razient/css/images/icons/* ajp13
JkMount /Razient/js/* ajp13
JkMount /Razient/servlet/* ajp13
JkMount /Razient/upload/* ajp13
JkMount /Razient/upload/kml/* ajp13
JkMount /Razient/upload/kml/customer/* ajp13
JkMount /Razient/upload/kml/supplier/* ajp13
JkMount /Razient/fusionchart/* ajp13
JkMount /Razient/fusionchart/customer/* ajp13
JkMount /Razient/fusionchart/supplier/* ajp13
JkMount /Razient/fusionchart/dashboard/* ajp13
JkMount /Razient/iconsgi/* ajp13
JkMount /Razient/xmlhttp/ ajp13

# Send everything for context /globalincidents to worker ajp13
JkMount /globalincidents ajp13
JkMount /globalincidents/* ajp13 

# Send everything for context /reports to worker ajp13
JkMount /reports ajp13
JkMount /reports/* ajp13 

# Send everything for context /reports to worker ajp13
JkMount /razresearch ajp13
JkMount /razresearch/* ajp13 

# Send everything for context /reports to worker ajp13
JkMount /RepSurveys ajp13
JkMount /RepSurveys/* ajp13 