/** 
 * beanLogins
 * Generated by MCM Software Solutions, Inc.
 *  JEvolution Studio ®  v 3.6.0.0 J2EE 1.4 Build 406-20110601120000 
 * Copyright © 2008 http://www.mcmsoftware.com
 * All Rights Reserved.
 */

package com.mcmsoftware.project; 
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Hashtable;
import java.util.Vector;
import com.mcmsoftware.jevolution.logicserver.beanlogin.BeanLoginInterface;

/** 
 *  Creation date: (2011/10/24 9:26:38 AM)
 *  @author:JEVOLUTION
 */

public class beanLogins implements BeanLoginInterface{
	public String user;
	public String password;
	public String ipAddress;
	public beanSesions beanSesion;

	public beanLogins(String user,String password, String address){
		this.user = user;
		this.password = password;
		this.ipAddress = address;
	}
	public String getUser(){
		return this.user;
	}
	public String getIpAddress(){
		return this.ipAddress;
	}
	public String getPassword(){
		return this.password;
	}
	public String getVariablesSesion(String atributo){
		return beanSesion.getVariablesBeanSesion(atributo);
	}
   public beanLogins validateAndLoadSesion(Connection con,beanLogins bean){
   		boolean bValidUser = false;
   		String strSqlSentence = "SELECT customersurveys.idcustomerSurveys FROM razient.customersurveys AS customersurveys WHERE (customersurveys.idcustomerSurveys=?) AND (customersurveys.idcustomerSurveys=?)";

		try{ 
			PreparedStatement ps = con.prepareStatement(strSqlSentence);
			ps.setObject(1,this.user);
			ps.setObject(2,this.password);
			ResultSet rs = ps.executeQuery();
			if(rs != null){
				while(rs.next()){
					bValidUser = true;
					/***Load BeanSesion ***/
					bean.setBeanSesion(new beanSesions(rs));
				}
				rs.close();
				ps.close();
				System.gc();
				if(bValidUser == true)
					return bean;
				else
					return null;
			}
			return null;
		}
		catch(Exception e){
			System.out.println(e.toString());
			return null;
		}
	}

	public void setBeanSesion(beanSesions beanSesion) {
		this.beanSesion = beanSesion;
	}
}
