/** 
 * beanSesions
 * Generated by MCM Software Solutions, Inc.
 *  JEvolution Studio ®  v 3.6.0.0 J2EE 1.4 Build 406-20110601120000 
 * Copyright © 2008 http://www.mcmsoftware.com
 * All Rights Reserved.
 */

package com.mcmsoftware.project; 
import java.sql.ResultSet;
/** 
 *  Creation date: (2011/10/24 9:26:38 AM)
 *  @author:JEVOLUTION
 */

public class beanSesions {

	/* VarSesions*/ 
	public String  cxRaz__razient__customersurveys__idcustomerSurveys;
	
	public beanSesions(ResultSet rs){
		loadVariablesBeanSesion(rs);
	}

	public String getVariablesBeanSesion(String atributo){
		String valorAtributoSesion =null;
		int posicionVariable = posicionVariableSesion(atributo);
		valorAtributoSesion = getVariablesPosicion(posicionVariable);
		return valorAtributoSesion;
	}

	private int posicionVariableSesion(String atributo){
		int posicion=-1;
		if(atributo.compareTo("cxRaz__razient__customersurveys__idcustomerSurveys")==0){
			posicion=1;	return posicion;
		}
	return posicion;
	}

	private String getVariablesPosicion(int posicionAtributo){
		String valorAtributo;
		switch (posicionAtributo) {
		case 1 :
			valorAtributo = this.getcxRaz__razient__customersurveys__idcustomerSurveys(); 
			break;
		default: valorAtributo = null; 
   			break;
  		}
  	return valorAtributo;
  	}

  	private void loadVariablesBeanSesion(ResultSet rs){
   	try{ 
			if(rs != null){
   			this.setcxRaz__razient__customersurveys__idcustomerSurveys(rs.getString(posicionVariableSesion("cxRaz__razient__customersurveys__idcustomerSurveys")));
   		}
		}
		catch(Exception e){
			System.out.println(e.toString());
		}
	}

	/* Method Get and Set : cxRaz__razient__customersurveys__idcustomerSurveys*/ 
   	private String getcxRaz__razient__customersurveys__idcustomerSurveys() {
   		return cxRaz__razient__customersurveys__idcustomerSurveys;
   	}
   	private void setcxRaz__razient__customersurveys__idcustomerSurveys(
   		String cxRaz__razient__customersurveys__idcustomerSurveys) {
   		this.cxRaz__razient__customersurveys__idcustomerSurveys = cxRaz__razient__customersurveys__idcustomerSurveys;
	}

}
