<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0" xmlns:js="javascript:code" 
			xmlns:java="http://xml.apache.org/xalan/java"
			exclude-result-prefixes="java"> 
<!-- 
     Generated by MCM Software Solutions, Inc.
      JEvolution Studio ®  v 3.5.0.0 J2EE 1.4 Build 405-20100805120000 
     Copyright © 2008 http://www.mcmsoftware.com
     All Rights Reserved.
 -->

  <xsl:param name="ReportCount" select="'default'"/>
  <xsl:param name="ReportPage" select="'default'"/>
  <xsl:param name="NameApp" select="'default'"/>
  <xsl:include href="xslpager.xsl"/>

  <xsl:decimal-format name="american"
               decimal-separator="."
               grouping-separator="," />

 <!-- Global Vars Session -->
 <!-- -->

<xsl:template match="Report"
	xmlns:java="http://xml.apache.org/xslt/java"
	xmlns:LogicServer="xalan://com.mcmsoftware.jevolution.logicserver.process.LogicServerServlet">
   <xsl:variable name="Cant">13</xsl:variable>
   <xsl:variable name="XbrfName">11011010brf</xsl:variable>
   <xsl:variable name="XslName">110QV7</xsl:variable>
   <xsl:variable name="Count"><xsl:value-of select="$ReportCount"/></xsl:variable>
   <xsl:variable name="Page"><xsl:value-of select="$ReportPage"/></xsl:variable>
   <html>
		<head><title>null</title>
		  <link rel="stylesheet" type="text/css" href="/{$NameApp}/CSSFiles/110QV7.css" />
		</head>
   <body bgcolor="#FFFFFF">
   <table cellspacing="0" cellpadding="0">
   <tr>
   	<td>
   	<img src="/{$NameApp}/jsp/images/historyback.jpg" onClick="history.go(-1)" />
       	</td>
   </tr>
   </table>
     <table align="Center" >
      <tr>
       <td>
          <table border="1" bgcolor="#BBBBBB" cellspacing="0">
            <tr>
            <th class="header" ID="printable_name" bgcolor="#FFFFFF">Country</th>
            <th class="header" ID="city" bgcolor="#FFFFFF">City</th>
            <th class="header" ID="state" bgcolor="#FFFFFF">State</th>
            </tr>
   <xsl:apply-templates select="resultset">
     <xsl:with-param name="count"><xsl:value-of select="$Count"/></xsl:with-param>
     <xsl:with-param name="cant"><xsl:value-of select="$Cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$Page"/></xsl:with-param>
   </xsl:apply-templates>
   </table>
   </td>
   </tr>
   <tr>
   <td ID="foot">
   <center>
   <br/>
   <xsl:call-template name="XSLPager">
      <xsl:with-param name="cant"><xsl:value-of select="$Cant"/></xsl:with-param>
      <xsl:with-param name="page"><xsl:value-of select="$Page"/></xsl:with-param>
      <xsl:with-param name="count"><xsl:value-of select="$Count"/></xsl:with-param>
      <xsl:with-param name="xbrfname"><xsl:value-of select="$XbrfName"/></xsl:with-param>
      <xsl:with-param name="xslname"><xsl:value-of select="$XslName"/></xsl:with-param>
   </xsl:call-template>
   </center>
   </td>
   </tr>
   </table>
   </body>
  </html>
</xsl:template>

<xsl:template match="resultset">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:apply-templates select="functions">
     <xsl:with-param name="cant"><xsl:value-of select="$cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$page"/></xsl:with-param>
     <xsl:with-param name="count"><xsl:value-of select="$count"/></xsl:with-param>
     <xsl:with-param name="breaksgroup" select="breaksgroup"/>
  </xsl:apply-templates>
</xsl:template>

<xsl:template match="functions">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:param name="breaksgroup"/>
   <xsl:variable name = "counttotal"><xsl:value-of select="counttotal" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countavg"><xsl:value-of select="countavg" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countmin"><xsl:value-of select="countmin" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countmax"><xsl:value-of select="countmax" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countfunct"><xsl:value-of select="countfunct" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countrows"><xsl:value-of select="countrows" disable-output-escaping="yes"/></xsl:variable>

   <xsl:variable name = "countcountbreak"><xsl:value-of select="countcountbreak" disable-output-escaping="yes"/></xsl:variable>
  <xsl:apply-templates select="function[position()&gt;0 and position()&lt;=$countfunct]" >
     <xsl:with-param name="cant"><xsl:value-of select="$cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$page"/></xsl:with-param>
     <xsl:with-param name="count"><xsl:value-of select="$count"/></xsl:with-param>
     <xsl:with-param name="breaksgroup" select="$breaksgroup"/>
     <xsl:with-param name="counttotal"><xsl:value-of select="$counttotal"/></xsl:with-param>
     <xsl:with-param name="countavg"><xsl:value-of select="$countavg"/></xsl:with-param>
     <xsl:with-param name="countmin"><xsl:value-of select="$countmin"/></xsl:with-param>
     <xsl:with-param name="countmax"><xsl:value-of select="$countmax"/></xsl:with-param>
     <xsl:with-param name="countfunct"><xsl:value-of select="$countfunct"/></xsl:with-param>
     <xsl:with-param name="countrows"><xsl:value-of select="$countrows"/></xsl:with-param>
     <xsl:with-param name="countcountbreak"><xsl:value-of select="$countcountbreak"/></xsl:with-param>
     <xsl:with-param name="colsgroup" select="colsgroup"/>
     <xsl:with-param name="countbreaktotal" select="countbreaktotal"/>
     <xsl:with-param name="totaltotal" select="totaltotal"/>
     <xsl:with-param name="avgtotal" select="avgtotal"/>
     <xsl:with-param name="mintotal" select="mintotal"/>
     <xsl:with-param name="maxtotal" select="maxtotal"/>
  </xsl:apply-templates>
</xsl:template>

<xsl:template match="function">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:param name="breaksgroup"/>
  <xsl:param name="countbreaktotal"/>
  <xsl:param name="counttotal"/>
  <xsl:param name="countavg"/>
  <xsl:param name="countmin"/>
  <xsl:param name="countmax"/>
  <xsl:param name="countfunct"/>
  <xsl:param name="countrows"/>
  <xsl:param name="countcountbreak"/>
  <xsl:param name="colsgroup"/>
  <xsl:param name="totaltotal"/>
  <xsl:param name="avgtotal"/>
  <xsl:param name="mintotal"/>
  <xsl:param name="maxtotal"/>
   <xsl:variable name = "begin"><xsl:value-of select="begin" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "end"><xsl:value-of select="end" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "total"><xsl:value-of select="total" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "avg"><xsl:value-of select="avg" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "min"><xsl:value-of select="min" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "max"><xsl:value-of select="max" disable-output-escaping="yes"/></xsl:variable>

   <xsl:variable name = "actual"><xsl:value-of select="@id" disable-output-escaping="yes"/></xsl:variable>

  <xsl:apply-templates select="rows" >
     <xsl:with-param name="cant"><xsl:value-of select="$cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$page"/></xsl:with-param>
     <xsl:with-param name="count"><xsl:value-of select="$count"/></xsl:with-param>
     <xsl:with-param name="begin"><xsl:value-of select="begin"/></xsl:with-param>
     <xsl:with-param name="end"><xsl:value-of select="end"/></xsl:with-param>
  </xsl:apply-templates>
		<xsl:if test="($end &gt;= $cant * ($page -1)) and ($end &lt; $cant * $page)">
		<xsl:variable name="countgroup"><xsl:value-of select="$countcountbreak -1" /></xsl:variable>

		<xsl:if test="($countgroup &gt;= 1) "><!-- More One break -->
			<xsl:for-each select="$colsgroup/column">
				<xsl:variable name="colsid"><xsl:value-of select="@id"/></xsl:variable>
				<xsl:variable name="showvalues"><xsl:value-of select="@showvalues" /></xsl:variable>
				<xsl:variable name="name"><xsl:value-of select="@name" /></xsl:variable>
 				<xsl:for-each select="$breaksgroup/resultcolumn">					
					<xsl:if test="@id  = $colsid  and $showvalues  = 'Yes'">
						<xsl:for-each select="resultfunction">
							<xsl:if test="$end  = endfunction ">
							</xsl:if>
						</xsl:for-each>
					</xsl:if>				
				</xsl:for-each> 
			</xsl:for-each>
		</xsl:if>
		</xsl:if>
		<xsl:if test="($countrows = $end+1) and (($page * $cant ) &gt;= $end+1)  ">
		</xsl:if>
</xsl:template>

<xsl:template match="rows">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:param name="begin"/>
  <xsl:param name="end"/>
		<xsl:if test="($begin &gt;= $cant * ($page -1)) and ($begin &lt; $cant * $page)">
			<xsl:if test="($end &lt; $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt;0 and position()&lt;= ($end+1 - $begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>
  			<tr>
  				<th colspan="3" bgcolor="#FFFFFF"><hr/></th>
  			</tr>
			</xsl:if>
			<xsl:if test="($end &gt;= $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt;0 and position()&lt;= (($page * $cant) - $begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>
  			<tr>
  				<th colspan="3" bgcolor="#FFFFFF"><hr/></th>
  			</tr>
			</xsl:if>
		</xsl:if>
		<xsl:if test="($begin &lt; $cant * ($page -1)) ">
			<xsl:if test="($end &gt;= $cant * ($page -1)) and ($end &lt; $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt; (($cant * ($page -1)) - $begin) and position()&lt;= ($end + 1 -$begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>
  			<tr>
  				<th colspan="3" bgcolor="#FFFFFF"><hr/></th>
  			</tr>
			</xsl:if>
			<xsl:if test="($end &gt;= $cant * ($page -1)) and ($end &gt;= $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt; (($cant * ($page -1)) - $begin) and position()&lt;= (($page * $cant) - $begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>  			<tr>
  				<th colspan="3" bgcolor="#FFFFFF"><hr/></th>
  			</tr>
			</xsl:if>
		</xsl:if>
</xsl:template>

<xsl:template match="row">
	<xsl:param name="begin"/>
	<xsl:variable name = "actual"><xsl:value-of select="@id"/></xsl:variable>

 	<!-- Params Session -->
 	<!-- -->

	<xsl:variable name="printable_name"><xsl:value-of select="country.printable_name" disable-output-escaping="no"/></xsl:variable>
	<xsl:variable name="city"><xsl:value-of select="city.city" disable-output-escaping="no"/></xsl:variable>
	<xsl:variable name="state"><xsl:value-of select="city.state" disable-output-escaping="no"/></xsl:variable>
   
	<xsl:if test="($begin = $actual)">
		<tr>
			<td ID="col_par" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000"><xsl:value-of select="country.printable_name" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
			</td>
			<td ID="col_impar" bgcolor="#FFFFFF" Align="Center">
       		<div>&#xa0;</div>
			</td>
			<td ID="col_par" bgcolor="#FFFFFF" Align="Center">
       		<div>&#xa0;</div>
			</td>
		</tr>
	</xsl:if>
	<tr>
		<xsl:if test="($actual mod 2 = 0)">
			<td class = "row_par" ID="col_par" bgcolor="#FFFFFF" Align="Center">
       		<div>&#xa0;</div>
			</td>
			<td class = "row_par" ID="col_impar" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000"><xsl:value-of select="city.city" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
			</td>
			<td class = "row_par" ID="col_par" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000"><xsl:value-of select="city.state" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
			</td>
		</xsl:if>
		<xsl:if test="($actual mod 2 = 1)">
			<td class = "row_impar" ID="col_par" bgcolor="#FFFFFF" Align="Center">
       		<div>&#xa0;</div>
			</td>
			<td class = "row_impar" ID="col_impar" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000"><xsl:value-of select="city.city" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
			</td>
			<td class = "row_impar" ID="col_par" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000"><xsl:value-of select="city.state" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
			</td>
		</xsl:if>
	</tr>
</xsl:template>

</xsl:stylesheet>

