<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.1" xmlns:js="javascript:code" 
			xmlns:java="http://xml.apache.org/xalan/java"
			exclude-result-prefixes="java"> 
<!-- 
     Generated by MCM Software Solutions, Inc.
      JEvolution Studio ®  v 3.6.0.0 J2EE 1.4 Build 406-20110601120000 
     Copyright © 2008 http://www.mcmsoftware.com
     All Rights Reserved.
 -->

  <xsl:param name="ReportCount" select="'default'"/>
  <xsl:param name="ReportPage" select="'default'"/>
  <xsl:param name="NameApp" select="'default'"/>
  <xsl:include href="xslpager.xsl"/>

  <xsl:decimal-format name="american"
               decimal-separator="."
               grouping-separator="," />

 <!-- Global Vars Session -->
 <!-- -->

<xsl:template match="Report"
	xmlns:java="http://xml.apache.org/xslt/java"
	xmlns:LogicServer="xalan://com.mcmsoftware.jevolution.logicserver.process.LogicServerServlet">
   <xsl:variable name="Cant">15</xsl:variable>
   <xsl:variable name="XbrfName">21021015brf</xsl:variable>
   <xsl:variable name="XslName">8BWF210SC15</xsl:variable>
   <xsl:variable name="Count">
         <xsl:value-of select="$ReportCount"/>
   </xsl:variable>
   <xsl:variable name="Page">
         <xsl:value-of select="$ReportPage"/>
   </xsl:variable>
   <html>
		<head><title>null</title>
		  <link rel="stylesheet" type="text/css" href="/{$NameApp}/CSSFiles/8BWF210SC15.css" />
		</head>
   <body bgcolor="#FFFFFF">
   <table cellspacing="0" cellpadding="0">
   <tr>
   	<td>
   	<img src="/{$NameApp}/jsp/images/historyback.jpg" onClick="history.go(-1)" />
       	</td>
   </tr>
   </table>
     <table align="Center" >
      <tr>
       <td>
          <table border="1" bgcolor="#BBBBBB" cellspacing="0">
            <tr>
            <th class="header" ID="city" bgcolor="#009999">City</th>
            <th class="header" ID="cf_ByIncidentTypebyCitydateNews3" bgcolor="#009999">Date</th>
            <th class="header" ID="type" bgcolor="#009999">Incident Type</th>
            <th class="header" ID="cf_mastersqltype2" bgcolor="#009999">Number of Incidents</th>
            </tr>
   <xsl:apply-templates select="resultset">
     <xsl:with-param name="count">
       <xsl:value-of select="$Count"/>
     </xsl:with-param>
     <xsl:with-param name="cant">
       <xsl:value-of select="$Cant"/>
     </xsl:with-param>
     <xsl:with-param name="page">
       <xsl:value-of select="$Page"/>
     </xsl:with-param>
   </xsl:apply-templates>
   </table>
   </td>
   </tr>
   <tr>
   <td ID="foot">
   <center>
   <br/>
   <xsl:call-template name="XSLPager">
      <xsl:with-param name="cant">
         <xsl:value-of select="$Cant"/>
      </xsl:with-param>
      <xsl:with-param name="page">
         <xsl:value-of select="$Page"/>
      </xsl:with-param>
      <xsl:with-param name="count">
        <xsl:value-of select="$Count"/>
      </xsl:with-param>
      <xsl:with-param name="xbrfname">
        <xsl:value-of select="$XbrfName"/>
      </xsl:with-param>
      <xsl:with-param name="xslname">
        <xsl:value-of select="$XslName"/>
      </xsl:with-param>
   </xsl:call-template>
   </center>
   </td>
   </tr>
   </table>
   </body>
  </html>
</xsl:template>

<xsl:template match="resultset">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:apply-templates select="row[position()&gt;($page*($cant)-($cant)) and position()&lt;=($page*$cant)]">
     <xsl:with-param name="cant">
       <xsl:value-of select="$cant"/>
     </xsl:with-param>
     <xsl:with-param name="page">
       <xsl:value-of select="$page"/>
     </xsl:with-param>
  </xsl:apply-templates>
 <xsl:choose>
 		<xsl:when test="( ($count&gt;$cant) and ( (($count - $cant)!= 1)or($page=1) ) )">
		</xsl:when>
 </xsl:choose>
 <xsl:choose>
 		<xsl:when test="((($page*$cant)&gt;=$count)and($count&gt;1))">
		</xsl:when>
 </xsl:choose>
</xsl:template>
<xsl:template match="row">
   <xsl:variable name = "actual">
      <xsl:value-of select="@id"/>
   </xsl:variable>
 	<!-- Params Session -->
 	<!-- -->

   <xsl:variable name = "newsdate">
      <xsl:value-of select="reportnewsglobalincident.cf_ByIncidentTypebyCitydateNews3" disable-output-escaping="yes"/>
   </xsl:variable>
   <xsl:variable name = "city">
      <xsl:value-of select="reportnewsglobalincident.city" disable-output-escaping="yes"/>
   </xsl:variable>
   <xsl:variable name = "type">
      <xsl:value-of select="reportnewsglobalincident.type" disable-output-escaping="yes"/>
   </xsl:variable>
   <xsl:variable name = "country">
      <xsl:value-of select="reportnewsglobalincident.country" disable-output-escaping="yes"/>
   </xsl:variable>
   <xsl:variable name = "state">
      <xsl:value-of select="reportnewsglobalincident.state" disable-output-escaping="yes"/>
   </xsl:variable>
      <xsl:variable name="country"><xsl:value-of select="reportnewsglobalincident.country" disable-output-escaping="no"/></xsl:variable>
      <xsl:variable name="state"><xsl:value-of select="reportnewsglobalincident.state" disable-output-escaping="no"/></xsl:variable>
      <xsl:variable name="city"><xsl:value-of select="reportnewsglobalincident.city" disable-output-escaping="no"/></xsl:variable>
      <xsl:variable name="cf_ByIncidentTypebyCitydateNews3"><xsl:value-of select="reportnewsglobalincident.cf_ByIncidentTypebyCitydateNews3" disable-output-escaping="yes"/></xsl:variable>
      <xsl:variable name="type"><xsl:value-of select="reportnewsglobalincident.type" disable-output-escaping="no"/></xsl:variable>
      <xsl:variable name="cf_mastersqltype2"><xsl:value-of select="reportnewsglobalincident.cf_mastersqltype2" disable-output-escaping="no"/></xsl:variable>
   
   <tr>
     <xsl:if test="($actual mod 2 = 0)">
       <td class = "row_par" ID="col_par" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000">     	<xsl:value-of select="reportnewsglobalincident.city" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
</td>
       <td class = "row_par" ID="col_impar" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000">     	<xsl:value-of select="reportnewsglobalincident.cf_ByIncidentTypebyCitydateNews3" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
</td>
       <td class = "row_par" ID="col_par" bgcolor="#FFFFFF" Align="Center">
         <A HREF = "/{$NameApp}/jsp/MCMBWF210SC16.jsp?&amp;@type={$type}&amp;@country={$country}&amp;@newsdate={$newsdate}&amp;@city={$city}&amp;@state={$state}" target="ResultDataEntry">
			<div align="Left">			<font color="#0000cc">     	<xsl:value-of select="reportnewsglobalincident.type" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
         </A>
</td>
       <td class = "row_par" ID="col_impar" bgcolor="#FFFFFF" Align="Center">
			<div align="Center">			<font color="#000000">     	<xsl:value-of select="reportnewsglobalincident.cf_mastersqltype2" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
</td>
     </xsl:if>
     <xsl:if test="($actual mod 2 = 1)">
       <td class = "row_impar" ID="col_par" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000">     	<xsl:value-of select="reportnewsglobalincident.city" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
</td>
       <td class = "row_impar" ID="col_impar" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000">     	<xsl:value-of select="reportnewsglobalincident.cf_ByIncidentTypebyCitydateNews3" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
</td>
       <td class = "row_impar" ID="col_par" bgcolor="#FFFFFF" Align="Center">
         <A HREF = "/{$NameApp}/jsp/MCMBWF210SC16.jsp?&amp;@type={$type}&amp;@country={$country}&amp;@newsdate={$newsdate}&amp;@city={$city}&amp;@state={$state}" target="ResultDataEntry">
			<div align="Left">			<font color="#0000cc">     	<xsl:value-of select="reportnewsglobalincident.type" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
         </A>
</td>
       <td class = "row_impar" ID="col_impar" bgcolor="#FFFFFF" Align="Center">
			<div align="Center">			<font color="#000000">     	<xsl:value-of select="reportnewsglobalincident.cf_mastersqltype2" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
</td>
     </xsl:if>
   </tr>
</xsl:template>

</xsl:stylesheet>

