FIELDSNUMBER
	fieldsnumber  = 16
	
LABEL
	label1.label  = REGULATIONNAME
	label2.label  = REGULATIONDESCRIPTION
	label3.label  = CATEGORYNAME
	label4.label  = SUBCATEGORYNAME
	label5.label  = TITLE
	label6.label  = DESCRIPTION
	label7.label  = QUESTIONTYPE
	label8.label  = QUESTIONCRITICALITY
	label9.label  = QUESTIONNAME
	label10.label  = QUESTIONDESCRIPTION
	label11.label  = SUPPORTINGINFORMATION
	label12.label  = QUESTIONBESTPRACTICE
	label13.label  = POSITION
	label14.label  = ISQUESTION
	label15.label  = ANSWERLABELS
	label16.label  = QUESTIONWEIGHT

TYPE
    	type1.type    = VARCHAR
    	type2.type    = VARCHAR
    	type3.type    = VARCHAR
    	type4.type    = VARCHAR
    	type5.type    = VARCHAR
    	type6.type    = VARCHAR
    	type7.type    = VARCHAR
    	type8.type    = VARCHAR
    	type9.type    = VARCHAR
    	type10.type    = VARCHAR
	type11.type    = VARCHAR
    	type12.type    = VARCHAR
    	type13.type    = INTEGER
    	type14.type    = VARCHAR
    	type15.type    = VARCHAR
    	type16.type    = INTEGER

LENGTH
    	length1.length  = 500
    	length2.length  = 2000
    	length3.length  = 500
    	length4.length  = 500
    	length5.length  = 500
    	length6.length  = 2000
    	length7.length  = 50
    	length8.length  = 50
    	length9.length  = 50
    	length10.length  = 5000
    	length11.length  = 5000
    	length12.length  = 5000
    	length13.length  = 5
    	length14.length  = 1
    	length15.length  = 100
    	length16.length  = 5

FORMAT
	format1.format = 
	format2.format = 
	format3.format = 
	format4.format = 
	format5.format = 
	format6.format = 
	format7.format = 
	format8.format = 
	format9.format =
	format10.format =
	format11.format =
	format12.format =
	format13.format =
	format14.format =
	format15.format =
	format16.format =	

	
PRECISION
	precision1.precision = 
	precision2.precision = 
	precision3.precision = 
	precision4.precision = 
	precision5.precision = 
	precision6.precision = 
	precision7.precision = 
	precision8.precision = 
	precision9.precision = 
	precision10.precision = 
	precision11.precision = 
	precision12.precision = 
	precision13.precision = 0
	precision14.precision = 
	precision15.precision = 
	precision16.precision = 0

NULLS
	null1.null = no
	null2.null = no
	null3.null = no
	null4.null = no
	null5.null = no
	null6.null = yes
	null7.null = no
	null8.null = no
	null9.null = no
	null10.null = no
	null11.null = yes
	null12.null = yes
	null13.null = no
	null14.null = no
	null15.null = yes
	null16.null = no
