<!-- 
     MCMloginTable110LT1.jsp
     Generated by MCM Software Solutions, Inc.
      JEvolution Studio ®  v 3.5.0.0 J2EE 1.4 Build 405-20100805120000 
     Copyright © 2008 http://www.mcmsoftware.com
     All Rights Reserved.
 -->

<html>
	<head>
		<title>logintable</title>
		<script language="javascript" src="js/validaCampos.js"></script>
		<script language="javascript">
		<!--
			function validaLogin(){
				event.returnValue = validaEntrada(forma.user);
			}
		-->
		</script>
	</head>
	<%@ page language="java" session="true" import="java.util.*" %>
	<%
	Hashtable   htSessionParams = new Hashtable(); 
	HttpSession sessions        = request.getSession();	
	htSessionParams   = (Hashtable)request.getSession().getAttribute("htParamsSession"); 

	session.invalidate();

	if(htSessionParams !=null)	 
		request.getSession().setAttribute("htParamsSession",htSessionParams);
		String error;
		error=request.getParameter("error");
		if( (error == null) || (error.equals("error")) )
			error="";
	%>

	<body bgcolor="#FFFFFF">
	<table width=100%>
		<tr><td>
			<table width=100% align="Center" border="0" bgcolor="#FFFFFF">
				<tr>
					<td align="center">
						<font size="3" face="Arial" color="#000000">Enter User and Password</font>
					</td>
				</tr>
				<tr><td></td></tr>
				<tr>
					<%
						if( (error == null) || (error.equals("error")) || (error.equals("null")) )  
							error="";
					%>
					<td align="center">
						<font size="3" face="Arial" color="#990000"><%= error %></font>
					</td>
				</tr>
			</table>
		</td></tr>
		<tr><td><br><br></td></tr>
		<tr><td>
		<form name="forma" method="POST" action="<%=request.getContextPath()%>/LogicServerAppServlet" target="_top" onSubmit="validaLogin();">
			<input type="hidden" name="requiredServlet" value="servletTable110LT1">
			<input type="hidden" name="typeLogin" value="TB">
			<table bgcolor="#FF3333" align="Center" border="0">
				<tr><td>
					<table>
						<tr>
							<td align="center"><font face="Arial" color="#000000" size="3" >User</font></td>
							<td><input type="text" name="user"></td>
						</tr>
						<tr>
							<td align="center"><font face="Arial" color="#000000" size="3" >Password</font></td>
							<td><input type="password" name="password"></td>
						</tr>
					</table>
				</td></tr>
				<tr><td></td></tr>
				<tr><td>
					<table width=100%>
						<tr>
							<td align="Center"><input type="submit" value="Submit"></td>
							<td align="Center"><input type="reset" value="Reset"></td>
						</tr>
					</table>
				</td></tr>
			</table>
		</form>
	</body>
</html>