<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0" xmlns:js="javascript:code" 
			xmlns:java="http://xml.apache.org/xalan/java"
			exclude-result-prefixes="java"> 
<!-- 
     Generated by MCM Software Solutions, Inc.
      JEvolution Studio ®  v 3.6.0.0 J2EE 1.4 Build 406-20110601120000 
     Copyright © 2008 http://www.mcmsoftware.com
     All Rights Reserved.
 -->

  <xsl:param name="ReportCount" select="'default'"/>
  <xsl:param name="ReportPage" select="'default'"/>
  <xsl:param name="NameApp" select="'default'"/>
  <xsl:include href="xslpager.xsl"/>

  <xsl:decimal-format name="american"
               decimal-separator="."
               grouping-separator="," />

 <!-- Global Vars Session -->
 <!-- -->

<xsl:template match="Report"
	xmlns:java="http://xml.apache.org/xslt/java"
	xmlns:LogicServer="xalan://com.mcmsoftware.jevolution.logicserver.process.LogicServerServlet">
   <xsl:variable name="Cant">15</xsl:variable>
   <xsl:variable name="XbrfName">21021049brf</xsl:variable>
   <xsl:variable name="XslName">23BWF210SC40</xsl:variable>
   <xsl:variable name="Count"><xsl:value-of select="$ReportCount"/></xsl:variable>
   <xsl:variable name="Page"><xsl:value-of select="$ReportPage"/></xsl:variable>
   <html>
		<head><title>null</title>
		  <link rel="stylesheet" type="text/css" href="/{$NameApp}/CSSFiles/23BWF210SC40.css" />
		</head>
   <body bgcolor="#FFFFFF">
   <table cellspacing="0" cellpadding="0">
   <tr>
   	<td>
   	<img src="/{$NameApp}/jsp/images/historyback.jpg" onClick="history.go(-1)" />
       	</td>
   </tr>
   </table>
 <table align="center">
      <tr>
       <td valign="top">
     <table align="Center" >
      <tr>
       <td>
          <table border="0" bgcolor="#BBBBBB" cellspacing="0">
            <tr>
            <th class="header">&#xa0;</th>
            <th class="header" ID="country" bgcolor="#009999">Country</th>
            <th class="header" ID="state" bgcolor="#009999">State</th>
            <th class="header" ID="type" bgcolor="#009999">Incident Type</th>
            <th class="header" ID="cf_Allincidentsbystate1latitude7" bgcolor="#009999">Number of Incidents</th>
            </tr>
   <xsl:apply-templates select="resultset">
     <xsl:with-param name="count"><xsl:value-of select="$Count"/></xsl:with-param>
     <xsl:with-param name="cant"><xsl:value-of select="$Cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$Page"/></xsl:with-param>
   </xsl:apply-templates>
   </table>
   </td>
   </tr>
   <tr>
   <td ID="foot">
   <center>
   <br/>
   <xsl:call-template name="XSLPager">
      <xsl:with-param name="cant"><xsl:value-of select="$Cant"/></xsl:with-param>
      <xsl:with-param name="page"><xsl:value-of select="$Page"/></xsl:with-param>
      <xsl:with-param name="count"><xsl:value-of select="$Count"/></xsl:with-param>
      <xsl:with-param name="xbrfname"><xsl:value-of select="$XbrfName"/></xsl:with-param>
      <xsl:with-param name="xslname"><xsl:value-of select="$XslName"/></xsl:with-param>
   </xsl:call-template>
   </center>
   </td>
   </tr>
   </table>
 		</td>
      	<td>
       <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
       	width="400" height="400" id="onechart"
       	codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0">
       	<param name="movie" value="jsp/fusioncharts/Pie3D.swf" />
       	<param name="FlashVars"
       		value="&amp;dataURL=jsp/fusioncharts/data/23BWF210SC40_1.xml" />
       	<param name="quality" value="high" />
       	<embed src="./jsp/fusioncharts/Pie3D.swf"
       		flashVars="&amp;dataURL=jsp/fusioncharts/data/23BWF210SC40_1.xml"
       		quality="high" width="400" height="400" name="onechart"
       		type="application/x-shockwave-flash"
       		pluginspage="http://www.macromedia.com/go/getflashplayer" />
       	</object>
       	<br/>
       	</td>
 </tr>
</table>
   </body>
  </html>
</xsl:template>

<xsl:template match="resultset">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:apply-templates select="functions">
     <xsl:with-param name="cant"><xsl:value-of select="$cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$page"/></xsl:with-param>
     <xsl:with-param name="count"><xsl:value-of select="$count"/></xsl:with-param>
     <xsl:with-param name="breaksgroup" select="breaksgroup"/>
  </xsl:apply-templates>
</xsl:template>

<xsl:template match="functions">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:param name="breaksgroup"/>
   <xsl:variable name = "counttotal"><xsl:value-of select="counttotal" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countavg"><xsl:value-of select="countavg" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countmin"><xsl:value-of select="countmin" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countmax"><xsl:value-of select="countmax" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countfunct"><xsl:value-of select="countfunct" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countrows"><xsl:value-of select="countrows" disable-output-escaping="yes"/></xsl:variable>

   <xsl:variable name = "countcountbreak"><xsl:value-of select="countcountbreak" disable-output-escaping="yes"/></xsl:variable>
  <xsl:apply-templates select="function[position()&gt;0 and position()&lt;=$countfunct]" >
     <xsl:with-param name="cant"><xsl:value-of select="$cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$page"/></xsl:with-param>
     <xsl:with-param name="count"><xsl:value-of select="$count"/></xsl:with-param>
     <xsl:with-param name="breaksgroup" select="$breaksgroup"/>
     <xsl:with-param name="counttotal"><xsl:value-of select="$counttotal"/></xsl:with-param>
     <xsl:with-param name="countavg"><xsl:value-of select="$countavg"/></xsl:with-param>
     <xsl:with-param name="countmin"><xsl:value-of select="$countmin"/></xsl:with-param>
     <xsl:with-param name="countmax"><xsl:value-of select="$countmax"/></xsl:with-param>
     <xsl:with-param name="countfunct"><xsl:value-of select="$countfunct"/></xsl:with-param>
     <xsl:with-param name="countrows"><xsl:value-of select="$countrows"/></xsl:with-param>
     <xsl:with-param name="countcountbreak"><xsl:value-of select="$countcountbreak"/></xsl:with-param>
     <xsl:with-param name="colsgroup" select="colsgroup"/>
     <xsl:with-param name="countbreaktotal" select="countbreaktotal"/>
     <xsl:with-param name="totaltotal" select="totaltotal"/>
     <xsl:with-param name="avgtotal" select="avgtotal"/>
     <xsl:with-param name="mintotal" select="mintotal"/>
     <xsl:with-param name="maxtotal" select="maxtotal"/>
  </xsl:apply-templates>
</xsl:template>

<xsl:template match="function">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:param name="breaksgroup"/>
  <xsl:param name="countbreaktotal"/>
  <xsl:param name="counttotal"/>
  <xsl:param name="countavg"/>
  <xsl:param name="countmin"/>
  <xsl:param name="countmax"/>
  <xsl:param name="countfunct"/>
  <xsl:param name="countrows"/>
  <xsl:param name="countcountbreak"/>
  <xsl:param name="colsgroup"/>
  <xsl:param name="totaltotal"/>
  <xsl:param name="avgtotal"/>
  <xsl:param name="mintotal"/>
  <xsl:param name="maxtotal"/>
   <xsl:variable name = "begin"><xsl:value-of select="begin" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "end"><xsl:value-of select="end" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "total"><xsl:value-of select="total" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "avg"><xsl:value-of select="avg" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "min"><xsl:value-of select="min" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "max"><xsl:value-of select="max" disable-output-escaping="yes"/></xsl:variable>

   <xsl:variable name = "actual"><xsl:value-of select="@id" disable-output-escaping="yes"/></xsl:variable>

  <xsl:apply-templates select="rows" >
     <xsl:with-param name="cant"><xsl:value-of select="$cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$page"/></xsl:with-param>
     <xsl:with-param name="count"><xsl:value-of select="$count"/></xsl:with-param>
     <xsl:with-param name="begin"><xsl:value-of select="begin"/></xsl:with-param>
     <xsl:with-param name="end"><xsl:value-of select="end"/></xsl:with-param>
  </xsl:apply-templates>
   <xsl:variable name="totalreportnewsglobalincident.cf_Allincidentsbystate1latitude7"><xsl:value-of select="total/reportnewsglobalincident.cf_Allincidentsbystate1latitude7" /></xsl:variable>
   <xsl:variable name="totaltotalreportnewsglobalincident.cf_Allincidentsbystate1latitude7"><xsl:value-of select="$totaltotal/reportnewsglobalincident.cf_Allincidentsbystate1latitude7" /></xsl:variable>
		<xsl:if test="($end &gt;= $cant * ($page -1)) and ($end &lt; $cant * $page)">
  			<tr>
  				<th colspan="6" bgcolor="#000000" align="Left"><font color="#000000"></font></th>
  			</tr>
  			<tr>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td align="right" bgcolor="#FFFFFF"><xsl:value-of select="format-number($totalreportnewsglobalincident.cf_Allincidentsbystate1latitude7,'#,##0.00','american')"/></td>
  			</tr>
  			<tr>
  				<th colspan="6" bgcolor="#FFFFFF"><hr/></th>
  			</tr>
		<xsl:variable name="countgroup"><xsl:value-of select="$countcountbreak -1" /></xsl:variable>

		<xsl:if test="($countgroup &gt;= 1) "><!-- More One break -->
			<xsl:for-each select="$colsgroup/column">
				<xsl:variable name="colsid"><xsl:value-of select="@id"/></xsl:variable>
				<xsl:variable name="showvalues"><xsl:value-of select="@showvalues" /></xsl:variable>
				<xsl:variable name="name"><xsl:value-of select="@name" /></xsl:variable>
 				<xsl:for-each select="$breaksgroup/resultcolumn">					
					<xsl:if test="@id  = $colsid  and $showvalues  = 'Yes'">
						<xsl:for-each select="resultfunction">
							<xsl:if test="$end  = endfunction ">
   								<xsl:variable name="grtotalreportnewsglobalincident.cf_Allincidentsbystate1latitude7"><xsl:value-of select="total/reportnewsglobalincident.cf_Allincidentsbystate1latitude7" /></xsl:variable>
							</xsl:if>
						</xsl:for-each>
					</xsl:if>				
				</xsl:for-each> 
			</xsl:for-each>
		</xsl:if>
		</xsl:if>
		<xsl:if test="($countrows = $end+1) and (($page * $cant ) &gt;= $end+1)  ">
  			<tr>
			<td bgcolor="#000000">Total Incidents&#xa0;</td>
			<td bgcolor="#000000">&#xa0;</td>
			<td bgcolor="#000000">&#xa0;</td>
			<td bgcolor="#000000">&#xa0;</td>
			<td align="right" bgcolor="#000000"><xsl:value-of select="format-number($totaltotalreportnewsglobalincident.cf_Allincidentsbystate1latitude7,'#,##0.00','american')"/></td>
  			</tr>
		</xsl:if>
</xsl:template>

<xsl:template match="rows">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:param name="begin"/>
  <xsl:param name="end"/>
		<xsl:if test="($begin &gt;= $cant * ($page -1)) and ($begin &lt; $cant * $page)">
			<xsl:if test="($end &lt; $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt;0 and position()&lt;= ($end+1 - $begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>
			</xsl:if>
			<xsl:if test="($end &gt;= $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt;0 and position()&lt;= (($page * $cant) - $begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>
			</xsl:if>
		</xsl:if>
		<xsl:if test="($begin &lt; $cant * ($page -1)) ">
			<xsl:if test="($end &gt;= $cant * ($page -1)) and ($end &lt; $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt; (($cant * ($page -1)) - $begin) and position()&lt;= ($end + 1 -$begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>
			</xsl:if>
			<xsl:if test="($end &gt;= $cant * ($page -1)) and ($end &gt;= $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt; (($cant * ($page -1)) - $begin) and position()&lt;= (($page * $cant) - $begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>			</xsl:if>
		</xsl:if>
</xsl:template>

<xsl:template match="row">
	<xsl:param name="begin"/>
	<xsl:variable name = "actual"><xsl:value-of select="@id"/></xsl:variable>

 	<!-- Params Session -->
 	<!-- -->

      <xsl:variable name="country"><xsl:value-of select="reportnewsglobalincident.country" disable-output-escaping="no"/></xsl:variable>
      <xsl:variable name="state"><xsl:value-of select="reportnewsglobalincident.state" disable-output-escaping="no"/></xsl:variable>
      <xsl:variable name="city"><xsl:value-of select="reportnewsglobalincident.city" disable-output-escaping="no"/></xsl:variable>
      <xsl:variable name="type"><xsl:value-of select="reportnewsglobalincident.type" disable-output-escaping="no"/></xsl:variable>
      <xsl:variable name="cf_Allincidentsbystate1latitude7"><xsl:value-of select="reportnewsglobalincident.cf_Allincidentsbystate1latitude7" disable-output-escaping="yes"/></xsl:variable>
   
	<xsl:if test="($begin = $actual)">
		<tr>
			<td bgcolor="#FFFFFF" ><div>&#xa0;</div></td>
			<td ID="col_par" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000"><xsl:value-of select="reportnewsglobalincident.country" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
			</td>
			<td ID="col_impar" bgcolor="#FFFFFF" Align="Center">
       		<div>&#xa0;</div>
			</td>
			<td ID="col_par" bgcolor="#FFFFFF" Align="Center">
       		<div>&#xa0;</div>
			</td>
			<td ID="col_impar" bgcolor="#FFFFFF" Align="Right">
       		<div>&#xa0;</div>
			</td>
		</tr>
	</xsl:if>
	<tr>
		<xsl:if test="($actual mod 2 = 0)">
			<td bgcolor="#FFFFFF"><div>&#xa0;</div></td>
			<td class = "row_par" ID="col_par" bgcolor="#FFFFFF" Align="Center">
       		<div>&#xa0;</div>
			</td>
			<td class = "row_par" ID="col_impar" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000"><xsl:value-of select="reportnewsglobalincident.state" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
			</td>
			<td class = "row_par" ID="col_par" bgcolor="#FFFFFF" Align="Center">
         <A HREF = "/{$NameApp}/jsp/MCMBWF210SC39.jsp?&amp;@state={$state}&amp;@type={$type}&amp;@country={$country}" target="ResultDataEntry">
			<div align="Left">			<font color="#0033cc"><xsl:value-of select="reportnewsglobalincident.type" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
         </A>
			</td>
			<td class = "row_par" ID="col_impar" bgcolor="#FFFFFF" Align="Right">
			<div align="Right">
			<font color="#000000">	<xsl:value-of select="java:com.mcmsoftware.jevolution.logicserver.utilities.FormatUtilities.getNumber($cf_Allincidentsbystate1latitude7,1,2)"/>&#xa0;
			</font>
			</div>
			</td>
     </xsl:if>
     <xsl:if test="($actual mod 2 = 1)">
			<td bgcolor="#FFFFFF"><div>&#xa0;</div></td>
			<td class = "row_impar" ID="col_par" bgcolor="#FFFFFF" Align="Center">
       		<div>&#xa0;</div>
			</td>
			<td class = "row_impar" ID="col_impar" bgcolor="#FFFFFF" Align="Center">
			<div align="Left">			<font color="#000000"><xsl:value-of select="reportnewsglobalincident.state" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
			</td>
			<td class = "row_impar" ID="col_par" bgcolor="#FFFFFF" Align="Center">
         <A HREF = "/{$NameApp}/jsp/MCMBWF210SC39.jsp?&amp;@state={$state}&amp;@type={$type}&amp;@country={$country}" target="ResultDataEntry">
			<div align="Left">			<font color="#0033cc"><xsl:value-of select="reportnewsglobalincident.type" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
         </A>
			</td>
			<td class = "row_impar" ID="col_impar" bgcolor="#FFFFFF" Align="Right">
			<div align="Right">
			<font color="#000000">	<xsl:value-of select="java:com.mcmsoftware.jevolution.logicserver.utilities.FormatUtilities.getNumber($cf_Allincidentsbystate1latitude7,1,2)"/>&#xa0;
			</font>
			</div>
			</td>
     </xsl:if>
   </tr>
</xsl:template>

</xsl:stylesheet>

