<!-- 
     MCMfwQVPDF.jsp
     Generated by MCM Software Solutions, Inc.
     JEvolution Studio ®  v 3.2.0.3 J2EE 1.4 Build 402-20090213120000 
     Copyright © 2009 http://www.mcmsoftware.com
     All Rights Reserved.
 -->

<%@ page import="java.net.*" %>

<% 
          
          boolean isElementOne = true;

          String strPdf       = null;
          String strPdfParam  = null;
          String strPdfParams = "";
          
          java.util.Enumeration paramNames = request.getParameterNames();
          
          String strHost    = "http://"+request.getServerName()+":"+request.getServerPort();
          String strAppName = request.getContextPath()+"/"+"LogicServerAppServlet"+"?";
			
          strPdf = ""+strHost+strAppName;
          
          while (paramNames.hasMoreElements())
          {
            String paramName = (String) paramNames.nextElement();
            try
            {
              String[] paramVals = request.getParameterValues(paramName);
              
              if (paramVals != null){
              
                  String encodedurl = URLEncoder.encode(paramVals[0],"UTF-8");
              
                  if(isElementOne){
                    strPdfParam = ""+ paramName +"="+ encodedurl;
                    isElementOne = false;
                  }
                  else
                    strPdfParam = "&"+ paramName +"="+ encodedurl;
                }
              strPdfParams = strPdfParams + strPdfParam;           
            }
            catch (Exception e)
            {}
          }
          strPdf = strPdf + strPdfParams;
%>

<%
	response.sendRedirect(strPdf);
%>

