<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0" xmlns:js="javascript:code" 
			xmlns:java="http://xml.apache.org/xalan/java"
			exclude-result-prefixes="java"> 
<!-- 
     Generated by MCM Software Solutions, Inc.
      JEvolution Studio ®  v 3.6.0.0 J2EE 1.4 Build 406-20110601120000 
     Copyright © 2008 http://www.mcmsoftware.com
     All Rights Reserved.
 -->

  <xsl:param name="ReportCount" select="'default'"/>
  <xsl:param name="ReportPage" select="'default'"/>
  <xsl:param name="NameApp" select="'default'"/>
  <xsl:include href="xslpager.xsl"/>

  <xsl:decimal-format name="american"
               decimal-separator="."
               grouping-separator="," />

 <!-- Global Vars Session -->
 <!-- -->

<xsl:template match="Report"
	xmlns:java="http://xml.apache.org/xslt/java"
	xmlns:LogicServer="xalan://com.mcmsoftware.jevolution.logicserver.process.LogicServerServlet">
   <xsl:variable name="Cant">25</xsl:variable>
   <xsl:variable name="XbrfName">61061056brf</xsl:variable>
   <xsl:variable name="XslName">610QV45</xsl:variable>
   <xsl:variable name="Count"><xsl:value-of select="$ReportCount"/></xsl:variable>
   <xsl:variable name="Page"><xsl:value-of select="$ReportPage"/></xsl:variable>
   <html>
		<head><title>Survey</title>
		  <link rel="stylesheet" type="text/css" href="/{$NameApp}/CSSFiles/610QV45.css" />
		</head>
   <body bgcolor="#FFFFFF">
   <table cellspacing="0" cellpadding="0">
   <tr>
   	<td>
   	<img src="/{$NameApp}/jsp/images/historyback.jpg" onClick="history.go(-1)" />
       	</td>
   </tr>
   </table>
     <table align="Center" >
      <tr>
       <td>
          <table border="0" bgcolor="#BBBBBB" cellspacing="0">
            <tr>
            <th class="header">&#xa0;</th>
            <th class="header" ID="sectionname" bgcolor="#FFFFFF">SECTION NAME</th>
            <th class="header" ID="question" bgcolor="#FFFFFF">QUESTION</th>
            <th class="header" ID="name" bgcolor="#FFFFFF">SUPPLIER NAME</th>
            <th class="header" ID="cf_SQLAnsweredSurveyXCustomercountryDesc10" bgcolor="#FFFFFF">ANSWER</th>
            <th class="header" ID="cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6" bgcolor="#FFFFFF">RATING</th>
            </tr>
   <xsl:apply-templates select="resultset">
     <xsl:with-param name="count"><xsl:value-of select="$Count"/></xsl:with-param>
     <xsl:with-param name="cant"><xsl:value-of select="$Cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$Page"/></xsl:with-param>
   </xsl:apply-templates>
   </table>
   </td>
   </tr>
   <tr>
   <td ID="foot">
   <center>
   <br/>
   <xsl:call-template name="XSLPager">
      <xsl:with-param name="cant"><xsl:value-of select="$Cant"/></xsl:with-param>
      <xsl:with-param name="page"><xsl:value-of select="$Page"/></xsl:with-param>
      <xsl:with-param name="count"><xsl:value-of select="$Count"/></xsl:with-param>
      <xsl:with-param name="xbrfname"><xsl:value-of select="$XbrfName"/></xsl:with-param>
      <xsl:with-param name="xslname"><xsl:value-of select="$XslName"/></xsl:with-param>
   </xsl:call-template>
   </center>
   </td>
   </tr>
   </table>
   </body>
  </html>
</xsl:template>

<xsl:template match="resultset">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:apply-templates select="functions">
     <xsl:with-param name="cant"><xsl:value-of select="$cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$page"/></xsl:with-param>
     <xsl:with-param name="count"><xsl:value-of select="$count"/></xsl:with-param>
     <xsl:with-param name="breaksgroup" select="breaksgroup"/>
  </xsl:apply-templates>
</xsl:template>

<xsl:template match="functions">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:param name="breaksgroup"/>
   <xsl:variable name = "counttotal"><xsl:value-of select="counttotal" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countavg"><xsl:value-of select="countavg" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countmin"><xsl:value-of select="countmin" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countmax"><xsl:value-of select="countmax" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countfunct"><xsl:value-of select="countfunct" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "countrows"><xsl:value-of select="countrows" disable-output-escaping="yes"/></xsl:variable>

   <xsl:variable name = "countcountbreak"><xsl:value-of select="countcountbreak" disable-output-escaping="yes"/></xsl:variable>
  <xsl:apply-templates select="function[position()&gt;0 and position()&lt;=$countfunct]" >
     <xsl:with-param name="cant"><xsl:value-of select="$cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$page"/></xsl:with-param>
     <xsl:with-param name="count"><xsl:value-of select="$count"/></xsl:with-param>
     <xsl:with-param name="breaksgroup" select="$breaksgroup"/>
     <xsl:with-param name="counttotal"><xsl:value-of select="$counttotal"/></xsl:with-param>
     <xsl:with-param name="countavg"><xsl:value-of select="$countavg"/></xsl:with-param>
     <xsl:with-param name="countmin"><xsl:value-of select="$countmin"/></xsl:with-param>
     <xsl:with-param name="countmax"><xsl:value-of select="$countmax"/></xsl:with-param>
     <xsl:with-param name="countfunct"><xsl:value-of select="$countfunct"/></xsl:with-param>
     <xsl:with-param name="countrows"><xsl:value-of select="$countrows"/></xsl:with-param>
     <xsl:with-param name="countcountbreak"><xsl:value-of select="$countcountbreak"/></xsl:with-param>
     <xsl:with-param name="colsgroup" select="colsgroup"/>
     <xsl:with-param name="countbreaktotal" select="countbreaktotal"/>
     <xsl:with-param name="totaltotal" select="totaltotal"/>
     <xsl:with-param name="avgtotal" select="avgtotal"/>
     <xsl:with-param name="mintotal" select="mintotal"/>
     <xsl:with-param name="maxtotal" select="maxtotal"/>
  </xsl:apply-templates>
</xsl:template>

<xsl:template match="function">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:param name="breaksgroup"/>
  <xsl:param name="countbreaktotal"/>
  <xsl:param name="counttotal"/>
  <xsl:param name="countavg"/>
  <xsl:param name="countmin"/>
  <xsl:param name="countmax"/>
  <xsl:param name="countfunct"/>
  <xsl:param name="countrows"/>
  <xsl:param name="countcountbreak"/>
  <xsl:param name="colsgroup"/>
  <xsl:param name="totaltotal"/>
  <xsl:param name="avgtotal"/>
  <xsl:param name="mintotal"/>
  <xsl:param name="maxtotal"/>
   <xsl:variable name = "begin"><xsl:value-of select="begin" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "end"><xsl:value-of select="end" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "total"><xsl:value-of select="total" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "avg"><xsl:value-of select="avg" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "min"><xsl:value-of select="min" disable-output-escaping="yes"/></xsl:variable>
   <xsl:variable name = "max"><xsl:value-of select="max" disable-output-escaping="yes"/></xsl:variable>

   <xsl:variable name = "actual"><xsl:value-of select="@id" disable-output-escaping="yes"/></xsl:variable>

  <xsl:apply-templates select="rows" >
     <xsl:with-param name="cant"><xsl:value-of select="$cant"/></xsl:with-param>
     <xsl:with-param name="page"><xsl:value-of select="$page"/></xsl:with-param>
     <xsl:with-param name="count"><xsl:value-of select="$count"/></xsl:with-param>
     <xsl:with-param name="begin"><xsl:value-of select="begin"/></xsl:with-param>
     <xsl:with-param name="end"><xsl:value-of select="end"/></xsl:with-param>
  </xsl:apply-templates>
   <xsl:variable name="avgvw_cussur_secque.cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6"><xsl:value-of select="avg/vw_cussur_secque.cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6" /></xsl:variable>
   <xsl:variable name="avgtotalvw_cussur_secque.cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6"><xsl:value-of select="$avgtotal/vw_cussur_secque.cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6" /></xsl:variable>
		<xsl:if test="($end &gt;= $cant * ($page -1)) and ($end &lt; $cant * $page)">
  			<tr>
  				<th colspan="10" bgcolor="#000000" align="Left"><font color="#000000">Answered</font></th>
  			</tr>
  			<tr>
			<td bgcolor="#FFFFFF">Average&#xa0;</td>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td align="right" bgcolor="#FFFFFF"><xsl:value-of select="format-number($avgvw_cussur_secque.cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6,'#,##0.00','american')"/></td>
  			</tr>
  			<tr>
  				<th colspan="10" bgcolor="#FFFFFF"><hr/></th>
  			</tr>
		<xsl:variable name="countgroup"><xsl:value-of select="$countcountbreak -1" /></xsl:variable>

		<xsl:if test="($countgroup &gt;= 1) "><!-- More One break -->
			<xsl:for-each select="$colsgroup/column">
				<xsl:variable name="colsid"><xsl:value-of select="@id"/></xsl:variable>
				<xsl:variable name="showvalues"><xsl:value-of select="@showvalues" /></xsl:variable>
				<xsl:variable name="name"><xsl:value-of select="@name" /></xsl:variable>
 				<xsl:for-each select="$breaksgroup/resultcolumn">					
					<xsl:if test="@id  = $colsid  and $showvalues  = 'Yes'">
						<xsl:for-each select="resultfunction">
							<xsl:if test="$end  = endfunction ">
   								<xsl:variable name="gravgvw_cussur_secque.cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6"><xsl:value-of select="avg/vw_cussur_secque.cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6" /></xsl:variable>
							</xsl:if>
						</xsl:for-each>
					</xsl:if>				
				</xsl:for-each> 
			</xsl:for-each>
		</xsl:if>
		</xsl:if>
		<xsl:if test="($countrows = $end+1) and (($page * $cant ) &gt;= $end+1)  ">
  			<tr>
			<td bgcolor="#FFFFFF">Average&#xa0;</td>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td bgcolor="#FFFFFF">&#xa0;</td>
			<td align="right" bgcolor="#FFFFFF"><xsl:value-of select="format-number($avgtotalvw_cussur_secque.cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6,'#,##0.00','american')"/></td>
  			</tr>
		</xsl:if>
</xsl:template>

<xsl:template match="rows">
  <xsl:param name="cant"/>
  <xsl:param name="page"/>
  <xsl:param name="count"/>
  <xsl:param name="begin"/>
  <xsl:param name="end"/>
		<xsl:if test="($begin &gt;= $cant * ($page -1)) and ($begin &lt; $cant * $page)">
			<xsl:if test="($end &lt; $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt;0 and position()&lt;= ($end+1 - $begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>
			</xsl:if>
			<xsl:if test="($end &gt;= $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt;0 and position()&lt;= (($page * $cant) - $begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>
			</xsl:if>
		</xsl:if>
		<xsl:if test="($begin &lt; $cant * ($page -1)) ">
			<xsl:if test="($end &gt;= $cant * ($page -1)) and ($end &lt; $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt; (($cant * ($page -1)) - $begin) and position()&lt;= ($end + 1 -$begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>
			</xsl:if>
			<xsl:if test="($end &gt;= $cant * ($page -1)) and ($end &gt;= $cant * $page)">
  				<xsl:apply-templates select="row[position()&gt; (($cant * ($page -1)) - $begin) and position()&lt;= (($page * $cant) - $begin)]" >
     				<xsl:with-param name="begin"><xsl:value-of select="$begin"/></xsl:with-param>
  				</xsl:apply-templates>			</xsl:if>
		</xsl:if>
</xsl:template>

<xsl:template match="row">
	<xsl:param name="begin"/>
	<xsl:variable name = "actual"><xsl:value-of select="@id"/></xsl:variable>

 	<!-- Params Session -->
	
	<xsl:variable name="format" select="string('yyyy-MM-dd')"/>
	<xsl:variable name="formatter"  select="java:java.text.SimpleDateFormat.new('MM/dd/yyyy')"/>
		
	
 	<!-- -->
	<xsl:variable name="notAnswered">Not Answered</xsl:variable>
	<xsl:variable name="idcustomerSurveys"><xsl:value-of select="vw_cussur_secque.idcustomerSurveys" disable-output-escaping="yes"/></xsl:variable>
	<xsl:variable name="customer_idCustomer"><xsl:value-of select="vw_cussur_secque.customer_idCustomer" disable-output-escaping="yes"/></xsl:variable>
	<xsl:variable name="surveyname"><xsl:value-of select="vw_cussur_secque.surveyname" disable-output-escaping="no"/></xsl:variable>
	<xsl:variable name="sectionname"><xsl:value-of select="vw_cussur_secque.sectionname" disable-output-escaping="no"/></xsl:variable>
	<xsl:variable name="question"><xsl:value-of select="vw_cussur_secque.question" disable-output-escaping="no"/></xsl:variable>
	<xsl:variable name="idSupplier"><xsl:value-of select="supplier.idSupplier" disable-output-escaping="yes"/></xsl:variable>
	<xsl:variable name="name"><xsl:value-of select="supplier.name" disable-output-escaping="no"/></xsl:variable>

	<xsl:variable name="cf_SQLAnsweredSurveyXCustomercountryDesc10">
		<xsl:value-of select="supplier.cf_SQLAnsweredSurveyXCustomercountryDesc10" disable-output-escaping="yes"/>
	</xsl:variable>	
	
	<xsl:variable name="cf_SQLAnsweredSurveyXCustomercountryDesc11">

		<xsl:choose>

			<xsl:when test="$cf_SQLAnsweredSurveyXCustomercountryDesc10 = 'null' or $cf_SQLAnsweredSurveyXCustomercountryDesc10 = ' '">

				<xsl:value-of select="$notAnswered"/>

			</xsl:when>

			<xsl:otherwise>

				<xsl:value-of select="$cf_SQLAnsweredSurveyXCustomercountryDesc10"/>

			</xsl:otherwise>

		</xsl:choose>

	</xsl:variable>

	<xsl:variable name="cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6"><xsl:value-of select="vw_cussur_secque.cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6" disable-output-escaping="yes"/></xsl:variable>
   
	<xsl:if test="($begin = $actual)">
		<tr>
			<td bgcolor="#FFFFFF" ><div>&#xa0;</div></td>
			<td ID="col_impar" bgcolor="#FFFFFF" Align="Left">
			<div align="Left">			<font color="#000000"><xsl:value-of select="vw_cussur_secque.sectionname" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
			</td>
			<td ID="col_par" bgcolor="#FFFFFF" Align="Left">
	<textarea name="" rows="4" readonly="" cols="40" wrap="hard" align="Left" style="color:#000000;" > 
<xsl:value-of select="vw_cussur_secque.question" disable-output-escaping="no"/>&#xa0;
	</textarea>
			</td>
			<td ID="col_impar" bgcolor="#FFFFFF" Align="Left">
       		<div>&#xa0;</div>
			</td>
			<td ID="col_par" bgcolor="#FFFFFF" Align="Left">
       		<div>&#xa0;</div>
			</td>
			<td ID="col_impar" bgcolor="#FFFFFF" Align="Right">
       		<div>&#xa0;</div>
			</td>
		</tr>
	</xsl:if>
	<tr>
		<xsl:if test="($actual mod 2 = 0)">
			<td bgcolor="#FFFFFF"><div>&#xa0;</div></td>
			<td class = "row_par" ID="col_impar" bgcolor="#FFFFFF" Align="Left">
       		<div>&#xa0;</div>
			</td>
			<td class = "row_par" ID="col_par" bgcolor="#FFFFFF" Align="Left">
       		<div>&#xa0;</div>
			</td>
			<td class = "row_par" ID="col_impar" bgcolor="#FFFFFF" Align="Left">
			<div align="Left">			<font color="#000000"><xsl:value-of select="supplier.name" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
			</td>
			<td class = "row_par" ID="col_par" bgcolor="#FFFFFF" Align="Left">
			<div align="Left">			<font color="#000000"><xsl:value-of select="$cf_SQLAnsweredSurveyXCustomercountryDesc11" disable-output-escaping="yes"/>&#xa0;
			</font>			</div>
			</td>
			<td class = "row_par" ID="col_impar" bgcolor="#FFFFFF" Align="Right">
			<div align="Right">
			<font color="#000000">	<xsl:value-of select="java:com.mcmsoftware.jevolution.logicserver.utilities.FormatUtilities.getNumber($cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6,1,2)"/>&#xa0;
			</font>
			</div>
			</td>
		</xsl:if>
		<xsl:if test="($actual mod 2 = 1)">
			<td bgcolor="#FFFFFF"><div>&#xa0;</div></td>
			<td class = "row_impar" ID="col_impar" bgcolor="#FFFFFF" Align="Left">
       		<div>&#xa0;</div>
			</td>
			<td class = "row_impar" ID="col_par" bgcolor="#FFFFFF" Align="Left">
       		<div>&#xa0;</div>
			</td>
			<td class = "row_impar" ID="col_impar" bgcolor="#FFFFFF" Align="Left">
			<div align="Left">			<font color="#000000"><xsl:value-of select="supplier.name" disable-output-escaping="no"/>&#xa0;
			</font>
			</div>
			</td>
			<td class = "row_impar" ID="col_par" bgcolor="#FFFFFF" Align="Left">
			<div align="Left">			<font color="#000000"><xsl:value-of select="$cf_SQLAnsweredSurveyXCustomercountryDesc11" disable-output-escaping="yes"/>&#xa0;
			</font>			</div>
			</td>
			<td class = "row_impar" ID="col_impar" bgcolor="#FFFFFF" Align="Right">
			<div align="Right">
			<font color="#000000">	<xsl:value-of select="java:com.mcmsoftware.jevolution.logicserver.utilities.FormatUtilities.getNumber($cf_SQLAnsweredSurveyXCustomerCASEWHENssralevelMarginalISNULLTHEN0ELSEssralevelMarginalENDASlevelMarginal6,1,2)"/>&#xa0;
			</font>
			</div>
			</td>
		</xsl:if>
	</tr>
</xsl:template>

</xsl:stylesheet>

