<!-- 
	Generated by MCM Software Solutions, inc.
	Ultima Actualizacion: 13-Agosto-2004
 	Copyright(c) 2004 http://www.mcmsoftware.com
	All Rights Reserved.
-->
<%@ page language="java" session="true" errorPage="error.jsp" %> 
<%
	String strError	= "";
	String strMessage = "";
	String strOutPutMessage="";
	String strBackPage="javascript:history.go(-1)";
	String strServletRequest="";
	String strProcess	= "ERROR";

	strServletRequest	= (String)session.getAttribute("ServletRequest");
	strError	= (String)request.getAttribute("Error");
	strMessage 	= request.getParameter("Message");

	if( (strServletRequest != null) && (!strServletRequest.equals("")) ){
		if( !strServletRequest.startsWith("/") )
			strServletRequest = strServletRequest.substring(2,strServletRequest.length());			
	}		
	if(strMessage != null){
		strBackPage = "javascript:history.back()";
		if(strMessage.equals("INSERTOK")){
			strOutPutMessage = "Insert Process Successful";	
			strProcess	= "OK";		
		}		
		else if(strMessage.equals("INSERTERROR")){
			strOutPutMessage = "Insert Process not Successful";
		}		
		else if(strMessage.equals("UPDATEOK")){
			strOutPutMessage = "Update Process Successful";
			strBackPage=strServletRequest;
			strProcess	= "OK";
		}		
		else if(strMessage.equals("UPDATEERROR")){
			strOutPutMessage = "Update Process not Successful";
		}
		else if(strMessage.equals("DELETEOK")){
			strOutPutMessage = "Delete Process Successful";
			strBackPage=strServletRequest;
			strProcess	= "OK";
		}
		else if(strMessage.equals("DELETEERROR")){
			strOutPutMessage = "Delete Process not Successful";
		}
            else{
			strOutPutMessage = strMessage;
			strProcess	= "WARNING";
            }
	}
      String comodin = "%25";
      String param = strBackPage;//el valor
      String nuevoparam = "";
      String letra;
   
      if ( param != null && !param.equals("") ){
          /* recorre el parametro caracter por caracter buscando el comodin (%) */
          for (int i=0; i<param.length(); i++){
              letra = String.valueOf( param.charAt(i) );
              if ( letra.equals("%") ){
                  letra = comodin;
              }
              nuevoparam = nuevoparam + letra;
          }
      }
      if( nuevoparam != null && !nuevoparam.equals( strBackPage ))
        strBackPage = nuevoparam;
%>
<html>
	<head>
		
	</head>
	<body>
		<font face="tahoma" color="black"/>
		<center>	
			<b>Process Summary</b><br>
			<img src="jsp/images/process_LINE.jpg" />	<br>			
			<img src="jsp/images/process_<%=strProcess%>.jpg" />
			<br>
			<h3><%=strOutPutMessage%></h3>
			<br>
			<font color="gray"><%=strError%>
			<br>
			<font color="blue">	
			<br>
			<a href="<%=strBackPage%>" style="color:white" ><img src="jsp/images/historyback.jpg"/></a>
		</center>
	</body>	
</html>