<!-- 
	Generated by MCM Software Solutions, inc.
	Ultima Actualizacion: 13-Julio-2004
 	Copyright(c) 2004 http://www.mcmsoftware.com
	All Rights Reserved.
-->
<%@ page language="java" import="java.util.Vector"%>
<%
	Vector vServletParameters=null;
	String strErrorMessage="";
	String strException="";
	String strAdvice="";
	vServletParameters = (Vector)session.getAttribute("vServletParameters");		
	strErrorMessage = (String)request.getAttribute("ErrorMessage");		
	strException = (String)request.getAttribute("Exception");
	strAdvice = (String)request.getAttribute("Advice");		
%>		
<html>
	<head>
		<title>Logic Server Console</title>			
	</head>
	<body>
		<font face="tahoma">
		<center>
			<br>
			<hr>
			<h1>LOGIC SERVER CONSOLE</h1>	
			<hr>
			<br>
			<h2><%= strAdvice %></h2>
			<br>
			ERROR:  <%= strException %>
			<br>
			<font color="6699FF"><%= strErrorMessage %></font>
			<br>
			<br>
			<font color="red">SERVLET PARAMETERS</font>
			<br>	
			<table border="1" align="center">
				<%
					if(vServletParameters!=null){
						int cont=0;
						while(cont<vServletParameters.size()){
							%>
							<tr>
								<td bgcolor="lightyellow"><%= (String)vServletParameters.elementAt(cont) %></td>
								<td><%= (String)vServletParameters.elementAt(cont+1) %></td>	
							</tr>
							<%	
							cont+=2;
						}
					}
				%>
			</table>
	</body>	
</html>