<!-- 
     MCMfw110QC13.jsp
     Generated by MCM Software Solutions, Inc.
      JEvolution Studio ®  v 3.5.0.0 J2EE 1.4 Build 405-20100805120000 
     Copyright © 2008 http://www.mcmsoftware.com
     All Rights Reserved.
 -->

<%@ page errorPage="error.jsp" import="com.mcmsoftware.project.beanLogins" %>
<%@ page language="java" session="true" %> 
<% 
	beanLogins bean =(beanLogins)session.getAttribute("User");
	String ipAddress;
	if(bean==null){ 
		response.sendRedirect("error.jsp");
	}
	else{
		ipAddress = bean.getIpAddress();
		if(!ipAddress.equals(request.getRemoteAddr()))
			response.sendRedirect("error.jsp");
	}
%>
<%
	HttpSession sesion = request.getSession(true);
	java.util.Enumeration e = request.getParameterNames();
	while (e.hasMoreElements()) {
	    String key = (String)e.nextElement();
	    String value = request.getParameter(key);
	    sesion.setAttribute(key,value);
	}
%>

<html>
	<jsp:forward page="/LogicServerAppServlet">
		<jsp:param name="NameXSL" value="5BWF110SC15"/>
		<jsp:param name="NameBODY" value="110QC13"/>
		<jsp:param name="sourceXBRF" value="11011014brf"/>
		<jsp:param name="Function" value="XBRFResolver"/>
	</jsp:forward>
</html>