/** 
 * 210QV13todate.js
 * Generated by MCM Software Solutions, Inc.
 *  JEvolution Studio ®  v 3.6.0.0 J2EE 1.4 Build 406-20110601120000 
 * Copyright © 2008 http://www.mcmsoftware.com
 * All Rights Reserved.
 */


   function y2k(number) { return (number < 1000) ? number + 1900 : number; }
   
var today  = new Date();
var day    = today.getDate();
var month  = today.getMonth();
var year   = y2k(today.getYear());
var time   = "00:00:00";
var format = "F8";

   function varFormat_todate() {
       format = "F8";
 	}

   function findName(parametro) {
     for(i=0; i<document.forma.length; i++){
       if(document.forma[i].name == parametro)
          return i;
     }
    return 0;
   }

   function padout(number) { return (number < 10) ? '0' + number : number; }
   
   function restarttodate() {
      bFormat = false;
      bVal = true;
      if(format == "F0" || format == "")
      	alert("Select a Date format");
      else {	
         id = findName("@todate");
         if (format == "F1")
            parameter = year + '/' + padout(month - 0 + 1) + '/' + padout(day);
         if (format == "F2")
            parameter = year + '-' + padout(month - 0 + 1) + '-' + padout(day);
         if (format == "F3")
            parameter = year + '' + padout(month - 0 + 1) + '' + padout(day);
         if (format == "F4")
            parameter = padout(day) + '/' + padout(month - 0 + 1) + '/' + year;
         if (format == "F5")
            parameter = padout(day) + '-' + padout(month - 0 + 1) + '-' + year;
         if (format == "F6")
            parameter = padout(day) + '' + padout(month - 0 + 1) + '' + year;
         if (format == "F7")
            parameter = padout(month - 0 + 1) + '/' + padout(day) + '/' + year;
         if (format == "F8")
            parameter = padout(month - 0 + 1) + '-' + padout(day) + '-' + year;
         if (format == "F9")
            parameter = padout(month - 0 + 1) + '' + padout(day) + '' +  year;
         if (format == "F11"){
            parameter = year + '/' + padout(month - 0 + 1) + '/' + padout(day);bFormat=true}
         if (format == "F12"){
            parameter = year + '-' + padout(month - 0 + 1) + '-' + padout(day);bFormat=true}
         if (format == "F13"){
            parameter = year + '' + padout(month - 0 + 1) + '' + padout(day);bFormat=true}
         if (format == "F14"){
            parameter = padout(day) + '/' + padout(month - 0 + 1) + '/' + year;bFormat=true}
         if (format == "F15"){
            parameter = padout(day) + '-' + padout(month - 0 + 1) + '-' + year;bFormat=true}
         if (format == "F16"){
            parameter = padout(day) + '' + padout(month - 0 + 1) + '' + year;bFormat=true}
         if (format == "F17"){
            parameter = padout(month - 0 + 1) + '/' + padout(day) + '/' + year;bFormat=true}
         if (format == "F18"){
            parameter = padout(month - 0 + 1) + '-' + padout(day) + '-' + year;bFormat=true}
         if (format == "F19"){
            parameter = padout(month - 0 + 1) + '' + padout(day) + '' +  year;bFormat=true}
         if(bFormat)
         	bVal = validateTimeClock(time);
         if(bVal){
         	if(bFormat)
         		document.forma[id].value = parameter + " "+time;
        		else
         		document.forma[id].value = parameter;

      	}
      	else
      		alert("hh:mm:ss Incorrecto");
         	mywindowtodate.close();
      }
   }

   function newWindowtodate() {
     varFormat_todate();
     mywindowtodate = open('210QV13todateCal.html','mynametodate','resizable=no,width=250,height=200,left=350,top=180');
     mywindowtodate.location.href = '210QV13todateCal.html';
     if (mywindowtodate.opener == null)
         mywindowtodate.opener = self;
   }

<!-- 210QV13todate.js -->

